# Generated by Django 4.1 on 2022-08-19 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_apies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 19, 14, 52, 51, 254384, tzinfo=datetime.timezone.utc)),
        ),
    ]
