# Generated by Django 4.1 on 2022-08-21 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_apies', '0002_alter_todo_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_finished',
            new_name='is_completed',
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
