# Generated by Django 4.1 on 2022-08-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('todo_list_apies', '0005_alter_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_token', to='authtoken.token'),
        ),
    ]
